:concurrency: 5
:timeout: 25
:verbose: false
:queues:
  - default
  - mailers
  - analytics
  - recommendations
  - inventory
  - payments

development:
  :concurrency: 2

production:
  :concurrency: 10
  :timeout: 30
